/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_NativeLib */

#ifndef _Included_org_example_NativeLib
#define _Included_org_example_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_NativeLib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_NativeLib_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_example_NativeLib
 * Method:    greet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_NativeLib_greet
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
